[project]
name = "firewxpy"
version = "1.0.0.73"
authors = [
  { name="Eric J Drewitz, USDA/USFS"},
]
description = "Weather Analysis and Forecasting For Fire Weather"
readme = "README.md"
keywords = ["meteorology", "science", "data-analysis", "weather", "forecasting"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
	"matplotlib>=3.7",
 	"protobuf==3.20.3",
	"metpy>=1.5.1",
	"netcdf4>=1.7.1",
	"numpy>=1.24",
	"pandas>=2",
	"siphon>=0.9",
	"xarray>=2023.1.0",
 	"xarray<=2024.02.0",
 	"pysolar>=0.11",
  	"pygrib>=2.1.4",
   	"cfgrib>=0.9.10.4",
    	"cartopy>=0.21.0",
     	"imageio>=2.34.0"
]

